mq_consumertest:mq_consumertest.cpp ../mqcommon/mq_msg.pb.cc
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_routetest:mq_routetest.cpp ../mqcommon/mq_msg.pb.cc
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_hosttest:mq_hosttest.cpp ../mqcommon/mq_msg.pb.cc
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_msgtest:mq_msgtest.cpp ../mqcommon/mq_msg.pb.cc
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_bindingtest:mq_bindingtest.cpp
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_queuetest:mq_queuetest.cpp
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_exchangetest:mq_exchangetest.cpp
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_filetest:mq_filetest.cpp
	g++ $^ -o $@ -std=c++11