mq_bindingtest:mq_bindingtest.cpp
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_queuetest:mq_queuetest.cpp
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_exchangetest:mq_exchangetest.cpp
	g++ $^ -o $@ -std=c++11 -lgtest -lprotobuf -lsqlite3
mq_filetest:mq_filetest.cpp
	g++ $^ -o $@ -std=c++11